### ISSUE TITLE
command improvement

### ISSUE THREAD

**Issue by Oreki-san** [ShinNouzen/Chitoge#8]
> some commands are giving error most of the time like haigusha,anime, character

> But mostly the `wallpaper` command is giving error please look into it

**Comment by LuckyYam** [comment]
Haigusha doesn't works cause it sometimes give undefined name. Anime and character maybe because of image processing error from [jimp](https://github.com/oliver-moran/jimp). And for wallpaper please check [this](https://github.com/iseizuu/anime-wallpaper/issues/4).  I can use other functions if you'd like but wallpapercave gives most of the sources so.
